export { gsap, useGSAP, ScrollTrigger, ScrollSmoother, SplitText, Observer, Flip, CustomEase, MOTION_OK, MOTION_REDUCED } from './gsap'
export { SmoothScroll } from './SmoothScroll'
export { GLLayer, GL_LAYER_ID, OVERLAY_LAYER_ID } from './GLLayer'
export { Stage3D } from './Stage3D'
export { useReducedMotion } from './useReducedMotion'
export { useSceneFrame } from './useSceneFrame'
export { createScrollValue, useScrollProgress, refreshScrollTriggers, type ScrollValue, type ScrollProgressOptions } from './scrollValue'
export { disposeObject3D, disposeMaterial, createDisposalBin } from './dispose'
export { detectTier, dprRange, supportsWebGL, isTouchPrimary, type DeviceTier } from './perf'
export { GPUStatsProbe, GPUStatsReadout, type GPUSnapshot } from './GPUStats'
export { navigate, usePathname } from './router'
